apiVersion: v1
kind: Service
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: songs-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: songs-ms
  template:
    metadata:
      labels:
        app: songs-ms
    spec:
      containers:
        - name: songs-ms
          image: songs-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SONGS_MS_NAME
              value: "songs-ms"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: SONGS_DB_URL
              value: "postgres"
            - name: SONGS_DB_PORT
              value: "5432"
          volumeMounts:
            - mountPath: /data
              name: songs-storage
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc
