apiVersion: v1
kind: Service
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: songs-ms
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-ms
  namespace: k8s-program
spec:
  serviceName: "songs-ms"
  replicas: 2
  selector:
    matchLabels:
      app: songs-ms
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: songs-ms
    spec:
      containers:
        - name: songs-ms
          image: songs-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: songs-ms
          env:
            - name: SONGS_MS_NAME
              value: "songs-ms"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: SONGS_DB_URL
              value: "postgres"
            - name: SONGS_DB_PORT
              value: "5432"
          volumeMounts:
            - mountPath: /data
              name: songs-storage
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: songs-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
